FROM node:18-alpine

WORKDIR /app

# Backend package.json is at ROOT
COPY package*.json ./

RUN npm install --omit=dev

# Copy backend source (root-level server.js, configs, etc.)
COPY . .


EXPOSE 5000

CMD ["npm", "start"]
